### ISSUE TITLE
Node.output is assumed to not change

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-dl#4] opened 2017-06-08 18:46 UTC
The current `nengo_dl.Simulator` assumes that `node.output` does not change after the model is built.  This means that it is possible to confuse the Simulator if those values are changed after build time:

```python
def test_node_output_change(Simulator, seed):
    for pre_val in [0, lambda t: 0]:
        for post_val in [1, lambda t: 1]:
            with nengo.Network(seed=seed) as net:
                inp = nengo.Node(pre_val)
                ens = nengo.Ensemble(n_neurons=100, dimensions=1)
                nengo.Connection(inp, ens)
                p = nengo.Probe(ens)

            with Simulator(net) as sim:
                inp.output = post_val
                sim.run(0.05)

            assert np.abs(np.mean(sim.data[p])-0.0) < 0.01
```

The sliders in `nengo_gui` require this feature for them to work!

**Comment by drasmuss** [comment] 2017-06-08 19:07
Including unit tests in the bug report :heart_eyes:

**Comment by drasmuss** [comment] 2017-06-08 20:44
Should be fixed if you want to check out the `change_nodes` branch.  Let me know if that works for you and I'll merge it into `master`

**Comment by drasmuss** [comment] 2017-06-09 18:44
Woops didn't mean to close this

**Comment by tcstewar** [comment] 2017-06-09 21:55
I haven't tested it yet as my computer seems to be annoyed at me trying to uninstall nengo_dl...  I'll take another stab at it this weekend....  :)

**Comment by drasmuss** [comment] 2018-06-06 12:47
@tcstewar I was just relooking at this (thinking about closing), and noticed something I missed the first time.  Your test code shows that the node output should _not_ change after `node.output` changes (i.e. the node continues to output 0.0, even though `post_val` is 1).  Is that the intended behaviour?  I had understood you the first time to be asking for the opposite.

**Comment by drasmuss** [comment] 2018-06-06 13:03
(woops, accidentally deleted comment, reposting)

@tcstewar I was just relooking at this, and noticed that your example shows that the output of the network does _not_ change after `node.output` changes (i.e. it continues to output 0.0, even though `post_val` is 1).  Is that the intended behaviour?  I had understood the first time that you wanted the output to change as `node.output` changes.

**Comment by tcstewar** [comment] 2018-06-06 13:10
> @tcstewar I was just relooking at this, and noticed that your example shows that the output of the network does not change after node.output changes (i.e. it continues to output 0.0, even though post_val is 1). Is that the intended behaviour? I had understood the first time that you wanted the output to change as node.output changes

The intended behaviour is that after the `Simulator` is built, if someone changes the `model`, there should be no change in the simulated behaviour.  The same thing would be true if someone adds `Connection`s or `Ensemble`s, or changing the properties of any of those things, so this is meant to be consistent with that.   So yes, it should continue to output 0, even though `post_val` is 1.   :)

**Comment by drasmuss** [comment] 2018-06-06 13:11
OK good, that's how I thought it should work, was confused why the GUI required that weird behaviour :smile:

**Closed** 2018-06-06 19:04 UTC
